### PR TITLE
Download S3 objects for different members to different local file

### PR DESCRIPTION
**Pull request by victoria-cherkas**
Fixes: 
* downloading S3 objects of different members to same local file

Refactors:
* Removes cli option --only
* Removes unused function restrict_grouped_setups
* Removes unused function write in setup_file.py

### CODE REVIEW

**Review by pirmink — APPROVED** [review]
All looks fine. Wouldn't have expected that much code just for a seemingly simple option. I agree to remove it to simplify the code.

**Comment by victoria-cherkas** [comment]
@pirmink thanks for the review, sorry I added more changes since, please can you also check these?

**Review by pirmink — APPROVED** [review]
Still looking good!

**Comment by victoria-cherkas** [comment]
Thanks!

**Pull request merged**
