### PR TITLE
New target install-opr and requirements cleanup.

### PR DESCRIPTION
**Pull request by pirmink**
The operational environment should be as lean as possible. To produce an environment.yml file accordingly, it must be possible to make a non-development installation that does not use environment.yml. I change the target install in the Makefile accordingly. For operational installation, I added a target install-opr, that does use the environment.yml.

The test target needs pytest, which was not installed with make install. I moved pytest from dev-requirements.in to requirements.in to allow testing also with a non-development version.

### CODE REVIEW

**Comment by ruestefa** [comment]
So do I understand this correctly: The problem are the dev-deps in environment.yml, so you only put the runtime deps in there and use unpinned deps for development and non-opr installs. How about creating a separate env file, e.g., dev-environment.yml, that contains all pinned deps (analogous to the various requirement.txt files)? That way you'd get a lean reproducible opr env alongside a reproducible dev env. The only reason not to use pinned deps so far was that this just didn't work properly pre-conda, now it should work.

**Comment by pirmink** [comment]
The Anaconda web page recommends fixing specific versions as little as possible, to allow conda to find a combination that satisfies all dependencies. Pinning is ok for an operational installation, where you want to reproduce exactly what has been tested, but pinning development versions potentially leads to the situation that you will never see updates to the dependencies and might one day depend on versions that are no longer supported. Thus I would prefer not to pin development installations, so that new versions in the dependencies become visible during develompment and can be handled properly.

**Comment by ruestefa** [comment]
OK, I see your point. Two counter-arguments:

- As long as the dependencies are still defined in `requirements.in`-Files, they are not "pinned" and can easily be brought up-to-date, whether there's a `dev-environment.yml` or not. If you don't do this regularly, you might work with slightly outdated versions, sure, but there's no barrier to staying up-to-date as there is if one defines _all_ requirements in a single, pinned `requirements.txt` (or `environment.yml`) w/o maintaining an unpinned equivalent.
- The versions of dev tools like `pylint`, `mypy` etc. should be pinned until updated manually, otherwise updates will regularly introduce new warnings/errors that require immediate action in the code and/or config (as long as everything should always be "green").
- Note that this is the case in `pre-commit`, which provides `pre-commit autoupdate` to update all checkers in `.pre-commit.yaml` to the latest versions, as well as in `tox`, which is provided a pinned `tox-requirements.txt` file. So as long as these frameworks are used to run checkers, there should be no surprises.
- I've also experienced version inconsistencies during development when going back and forth between my laptop and tsa, which would have been eliminated by a pinned environment, and the same can happen on a single machine that is updated. This can lead to nasty bugs like a test validating on one machine but not on another. This is now mitigated by `conda`, which leaves less up to the machine and leads to more reproducibility by default. On the other hand, `conda` also facilitates working in pinned environments, so why not take advantage of that.

To conclude, personally I would go for pinning even the dev environment (and updating it regularly with `make update-dev-env`, which could even also update the pinned tox and pre-commit dependencies), mainly in order to hop between machines w/o any surprises.

But feel free to disagree and go w/o a pinned dev environment. :)

**Comment by pirmink** [comment]
So I removed the install-opr target and updated the update-run-deps and update-run-dev-deps targets in the Makefile, which now create a new unpinned installation and derive the environment.yml file from it.

**Pull request closed without merging**
